interactions:
- request:
    body: '{"type": "string"}'
    headers:
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      Content-Length:
      - '18'
      User-Agent:
      - python-requests/2.24.0
      accept:
      - application/json
      content-type:
      - application/json
    method: PUT
    uri: http://localhost:8080/API/metadata-field/fieldone
  response:
    body:
      string: '{"notFound":null,"internalServer":null,"forbidden":null,"notYetImplemented":null,"conflict":null,"invalidInput":{"context":"metadata-field","id":"fieldone","explanation":"The
        name of the metadata field is invalid","value":"fieldone"},"licenseFault":null,"fileAlreadyExists":null,"notAuthorized":null}'
    headers:
      Content-Length:
      - '300'
      Content-Type:
      - application/json
      Date:
      - Mon, 28 Sep 2020 11:24:49 GMT
      Set-Cookie:
      - rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Sun, 27-Sep-2020 11:24:49
        GMT
    status:
      code: 400
      message: Bad Request
version: 1
